### ISSUE TITLE
The readme for exercise 2 missing step to uncomment import

### ISSUE THREAD

**Issue by am-MongoDB** [aydrian/workshop-picstream#4]
The exercise instructions should include uncommenting these lines (or at least the Stitch part)...

```js
/*import {
  Stitch,
  UserPasswordCredential,
  RemoteMongoClient
} from 'mongodb-stitch-browser-sdk'
import {
  AwsServiceClient,
  AwsRequest
} from 'mongodb-stitch-browser-services-aws'*/
```

**Comment by aydrian** [comment]
Good catch. Those should have been uncommented. I was just hiding warnings. We don't need the user to uncomment them, I just went ahead and did it.
